# Generated by Django 4.2.9 on 2024-01-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
