# Generated by Django 4.2.9 on 2024-02-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_thumnail_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('pb', 'Publish'), ('pd', 'Pending'), ('b', 'Back')], max_length=2),
        ),
    ]
